notifications:
  recipients:
    - kou@cozmixng.org
addons:
  postgresql: "9.4"
install:
  - curl --silent --location https://github.com/pgroonga/pgroonga/raw/master/data/travis/setup.sh | sh
before_script:
  - psql -c 'CREATE DATABASE pgroonga_test;'
  - psql -d pgroonga_test -c 'CREATE EXTENSION pgroonga;'
script:
  - psql -d pgroonga_test -f test.sql
